name: Nightly Releases

on:
  push:
    branches: [ dev, ci/** ]

jobs:
  docs:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4      
      - uses: flucoma/actions/maxdocs@v4

      - uses: actions/upload-artifact@v2
        with:
          name: docsbuild
          path: build/max_ref

  winbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: flucoma/actions/env@v4
    - uses: flucoma/actions/max@v4

    - uses: actions/upload-artifact@v2
      with:
        name: winbuild
        path: "release-packaging/FluidCorpusManipulation/externals/"
  
  macbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
      - uses: flucoma/actions/max@v4

      - uses: actions/upload-artifact@v2
        with:
          name: macbuild
          path: release-packaging/FluidCorpusManipulation/
  
  release:
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    needs: [winbuild, macbuild, docs]

    steps:
      - name: make parent folder
        run : mkdir -p "FluidCorpusManipulation"

      - uses: actions/download-artifact@v2
        with:
          name: macbuild
          path: "FluidCorpusManipulation"

      - uses: actions/download-artifact@v2
        with:
          name: winbuild
          path: "FluidCorpusManipulation/externals"
  
      - uses: actions/download-artifact@v2
        with:
          name: docsbuild
          path: "FluidCorpusManipulation/docs"
      
      - name: zip
        run: zip -r FluCoMa-Max-nightly.zip "FluidCorpusManipulation"

      - name: see
        run: ls

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: nightly # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: package and upload
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: FluCoMa Max Nightly Build
          prerelease: true
          body: "This is a nightly build of the FluCoMa Max package. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FluCoMa-Max-nightly.zip
          asset_name: FluCoMa-Max-nightly.zip
          tag: nightly
          overwrite: true
